// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data.Model
{

    // Order
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Order
    {
        public int OrderId { get; set; } // OrderId (Primary key)
        public int CustomerId { get; set; } // CustomerId
        public System.DateTime? OrderDate { get; set; } // OrderDate
        public int? OrderQuantity { get; set; } // OrderQuantity

        // Foreign keys
        public virtual Customer Customer { get; set; } // FK_Order_Customer
    }

}
// </auto-generated>
